---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install resume-cli
      - run: npx resume validate
      - uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          file_path: resume.json
          gist_id: ${{ vars.GIST_ID }}
          token: ${{ secrets.TOKEN }}

on:
  push:
    branches: [main]
  workflow_dispatch:
